# Configuration Sonar
sonar.projectKey=manue-tasklist-frontend
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr

# 1. Déclarer le dossier source principal
sonar.sources=src

# 2. Exclure le dossier de tests des sources (pour qu'il ne demande pas de couverture)
sonar.exclusions=**/__tests__/**,node_modules/**,dist/**,coverage/**


# 3. Indiquer explicitement où se trouvent les tests
sonar.tests=src/__tests__